"Client implementation to interact with the Shokunin motion planning service."

module(name = "planning_service_client")

# C++ rules
bazel_dep(name = "rules_cc", version = "0.2.17")

# Platform constraints (used by many Bazel rulesets)
bazel_dep(name = "platforms", version = "1.0.0")

# Python rules
bazel_dep(name = "rules_python", version = "1.9.0")

# Pybind11 (for C++ -> Python bindings)
bazel_dep(name = "pybind11_bazel", version = "3.0.1")

# GTest
bazel_dep(name = "googletest", version = "1.17.0")

# Protobuf
bazel_dep(name = "protobuf", version = "29.5")

# Magic enum
bazel_dep(name = "magic_enum", version = "0.9.7")

# gRPC
bazel_dep(name = "grpc", version = "1.70.1")

# Eigen
bazel_dep(name = "eigen", version = "3.4.1")

# JSON
bazel_dep(name = "nlohmann_json", version = "3.12.0")

# Python
python = use_extension("@rules_python//python/extensions:python.bzl", "python")

# Default to 3.12; support 3.10-3.13.
python.defaults(python_version = "3.12")
python.toolchain(python_version = "3.10")
python.toolchain(python_version = "3.11")
python.toolchain(python_version = "3.12")
python.toolchain(python_version = "3.13")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "planning_service_client_dependencies",
    python_version = "3.10",
    requirements_lock = "client/python/planning_service_client/requirements.txt",
)
pip.parse(
    hub_name = "planning_service_client_dependencies",
    python_version = "3.11",
    requirements_lock = "client/python/planning_service_client/requirements.txt",
)
pip.parse(
    hub_name = "planning_service_client_dependencies",
    python_version = "3.12",
    requirements_lock = "client/python/planning_service_client/requirements.txt",
)
pip.parse(
    hub_name = "planning_service_client_dependencies",
    python_version = "3.13",
    requirements_lock = "client/python/planning_service_client/requirements.txt",
)
use_repo(pip, "planning_service_client_dependencies")
