/*
 * Copyright © 2023 Dexai Robotics. All rights reserved.
 */
#include <filesystem>

#include "CLI/CLI.hpp"
#include "planning_service/common/file_utils.h"
#include "planning_service/common/logging.h"

namespace fs = std::filesystem;

/**
 * @brief Get all URDFs which are not used in the DMD of any context.
 *
 * @param urdf_dir Directory containing all URDFs
 * @param context_dir Directory containing all contexts
 * @return std::pair<std::vector<fs::path>, int> Pair containing the vector of
 * unused URDFs and the total number of URDFs in the directory.
 */
std::pair<std::vector<fs::path>, int> get_unused_urdfs(
    const fs::path& urdf_dir, const fs::path& context_dir) {
  std::vector<fs::path> unused_urdfs;
  int count {0};
  for (const auto& entry : fs::recursive_directory_iterator(urdf_dir)) {
    const auto path {entry.path()};
    if (entry.is_directory() || path.extension() != ".urdf") {
      continue;
    }
    ++count;
    const auto urdf_name {path.filename()};
    bool found {false};
    // Check if the URDF is referenced in any DMD.
    for (const auto& context_entry : fs::directory_iterator(context_dir)) {
      const auto context_path {context_entry.path()};
      const auto dmd_path {context_path / "dmd.yaml"};
      if (common::utils::StringInFile(dmd_path, urdf_name)) {
        logging::log()->debug("get_unused_urdfs: Found URDF {} in DMD {}",
                              urdf_name, dmd_path);
        found = true;
        break;
      }
    }
    if (!found) {
      unused_urdfs.push_back(path);
    }
  }
  return std::make_pair(unused_urdfs, count);
}

/**
 * @brief Get all meshes which are not used in any URDF file
 *
 * @param mesh_dir
 * @param urdf_dir
 * @return std::pair<std::vector<fs::path>, int>
 */
std::pair<std::vector<fs::path>, int> get_unused_meshes(
    const fs::path& mesh_dir, const fs::path& urdf_dir) {
  std::vector<fs::path> unused_meshes;
  int count {0};
  for (const auto& entry : fs::recursive_directory_iterator(mesh_dir)) {
    const auto path {entry.path()};
    if (entry.is_directory()
        || (path.extension() != ".stl" && path.extension() != ".obj")) {
      continue;
    }
    ++count;
    bool found {false};
    const auto relpath {fs::relative(path, mesh_dir)};
    for (const auto& urdf_entry : fs::recursive_directory_iterator(urdf_dir)) {
      const auto urdf_path {urdf_entry.path()};
      if (urdf_entry.is_directory() || urdf_path.extension() != ".urdf") {
        continue;
      }
      if (common::utils::StringInFile(urdf_path, relpath.string())) {
        logging::log()->debug("get_unused_meshes: Found mesh {} in URDF {}",
                              relpath, urdf_path);
        found = true;
        break;
      }
    }
    if (!found) {
      unused_meshes.push_back(path);
    }
  }
  return std::make_pair(unused_meshes, count);
}

int main(int argc, char* argv[]) {
  logging::create_log("remove_unused_urdfs");
  //// Create command line interface
  CLI::App app {"Remove old URDFs which are not referenced in any DMD"};
  std::string system_name {""};
  app.add_option("system_name", system_name,
                 "Target system and top-level namespace for all data consumed "
                 "and generated by the application")
      ->required();
  bool yes {false};
  app.add_flag("-y,--yes", yes, "Delete all unused URDFs without confirmation");

  CLI11_PARSE(app, argc, argv);

  if (system_name.empty()) {
    logging::log()->error("System name is empty!");
    return 1;
  }
  const fs::path data_root {"/data"};
  if (!fs::is_directory(data_root / system_name)) {
    logging::log()->error("System {} does not exist!", system_name);
    return 1;
  }
  logging::log()->set_level(spdlog::level::debug);
  logging::log()->info("Evaluating URDFS for system '{}'...", system_name);
  const fs::path urdf_dir {data_root / system_name / "urdf"};
  const fs::path mesh_dir {urdf_dir / "meshes"};
  const fs::path context_dir {data_root / system_name / "contexts"};
  const auto& [unused_urdfs,
               num_urdfs] {get_unused_urdfs(urdf_dir, context_dir)};
  logging::log()->info("Found {}/{} unused URDFs.", unused_urdfs.size(),
                       num_urdfs);
  for (const auto& path : unused_urdfs) {
    logging::log()->info("  {}", path);
  }

  if (!yes && !unused_urdfs.empty()) {
    logging::log()->info("Delete all? [y/N]");
    std::string response;
    std::cin >> response;
    // get the first character, and lowercase it
    yes = std::tolower(response[0]) == 'y';
  }
  if (yes) {
    for (const auto& path : unused_urdfs) {
      fs::remove(path);
    }
    logging::log()->info("Deleted {} URDFs.", unused_urdfs.size());
  }
  // Reset yes flag
  yes = false;
  logging::log()->info("Evaluating meshes for system '{}'...", system_name);
  const auto& [unused_meshes,
               num_meshes] {get_unused_meshes(mesh_dir, urdf_dir)};
  logging::log()->info("Found {}/{} unused meshes.", unused_meshes.size(),
                       num_meshes);
  for (const auto& path : unused_meshes) {
    logging::log()->info("  {}", path);
  }
  if (!yes && !unused_meshes.empty()) {
    logging::log()->info("Delete all? [y/N]");
    std::string response;
    std::cin >> response;
    // get the first character, and lowercase it
    yes = std::tolower(response[0]) == 'y';
  }
  if (yes) {
    for (const auto& path : unused_meshes) {
      fs::remove(path);
    }
    logging::log()->info("Deleted {} meshes.", unused_meshes.size());
  }
  return 0;
}
