/*
 * Copyright © 2023 Dexai Robotics. All rights reserved.
 */

#include "CLI/CLI.hpp"
#include "planning_service/service/utils/resource_registry.h"

namespace fs = std::filesystem;
// Iterate over all the URDFs and check if they are referenced in any DMD.
int main(int argc, char* argv[]) {
  logging::create_log("remove_invalid_contexts");
  //// Create command line interface
  CLI::App app {"Remove contexts which have become invalid."};
  std::string system_name {""};
  app.add_option("system_name", system_name,
                 "Target system and top-level namespace for all data consumed "
                 "and generated by the application")
      ->required();
  bool yes {false};
  app.add_flag("-y,--yes", yes,
               "Delete all invalid contexts without confirmation");
  CLI11_PARSE(app, argc, argv);

  if (system_name.empty()) {
    logging::log()->error("System name is empty!");
    return 1;
  }
  service::utils::ResourceOptions options;
  options.require_parameters = true;
  options.require_all_resources = false;
  const auto registry {
      std::make_unique<service::utils::ResourceRegistry>(system_name, options)};
  std::vector<fs::path> invalid_contexts;
  int count {0};
  for (const auto& entry :
       fs::directory_iterator(registry->context_base_path())) {
    const auto context_path {entry.path()};
    if (entry.is_directory()) {
      ++count;
      const auto context_id {std::stoull(context_path.stem().string())};
      if (!registry->HasDraco(context_id)) {
        invalid_contexts.push_back(context_path);
      }
    }
  }
  if (invalid_contexts.empty()) {
    logging::log()->info("No invalid contexts found for system {}. Nice.",
                         system_name);
    return 0;
  }
  logging::log()->info("Found {}/{} invalid contexts for system '{}':",
                       invalid_contexts.size(), count, system_name);
  for (const auto& context_path : invalid_contexts) {
    logging::log()->info("  {}", context_path);
  }
  if (!yes) {
    logging::log()->info("Delete all? [y/N]");
    std::string response;
    std::cin >> response;
    // get the first character, and lowercase it
    yes = std::tolower(response[0]) == 'y';
  }
  if (yes) {
    for (const auto& path : invalid_contexts) {
      fs::remove_all(path);
    }
    logging::log()->info("Deleted {} context(s)", invalid_contexts.size());
  } else {
    logging::log()->info("No contexts deleted.");
  }

  return 0;
}
