/*
 * Copyright © 2023 Dexai Robotics. All rights reserved.
 */

#include <cstdlib>

#include <grpc/grpc.h>
#include <grpcpp/channel.h>
#include <grpcpp/client_context.h>
#include <grpcpp/create_channel.h>
#include <grpcpp/security/credentials.h>

#include "planning_service/common/file_utils.h"
#include "planning_service/comms/server_wrapper.h"
#include "planning_service/comms/utils.h"
#include "planning_service/service/utils/resource_registry.h"
#include "planning_service/service/utils/utils.h"
#include "proto/basic_types.pb.h"
#include "proto/builder.grpc.pb.h"
#include "proto/planner.grpc.pb.h"
#include "proto/registry.grpc.pb.h"

namespace comms {
namespace test {

/**
 * @brief Test fixture template used to test a given service against its
 * corresponding stub. Given an autogenerated gRPC service `MyGrpcService`, the
 * corresponding test fixture would have the form:
 * class MyGrpcServiceTest :
 *   public ServiceTest<MyGrpcServiceImpl, MyGrpcService::Stub> {...}
 *
 * where MyGrpcServiceImpl is derived from MyGrpcService::Service.
 *
 * @tparam TService
 * @tparam TStub
 */
template <typename TService, typename TStub>
class ServiceTest : public ::testing::Test {
  static_assert(std::is_base_of_v<grpc::Service, TService>,
                "Template parameter TService must derive from grpc::Service");

 protected:
  void SetUp() override {
    // setup the data
    temp_dir_ = common::utils::temp_dir();
    const fs::path iiwa_data_dir {"planning_service/test_data/iiwa/"};
    const auto temp_iiwa_data_dir {temp_dir_ / "iiwa"};
    fs::create_directories(temp_iiwa_data_dir);
    fs::copy(iiwa_data_dir, temp_iiwa_data_dir,
             fs::copy_options::recursive | fs::copy_options::update_existing);
    options_.data_path_root_override = temp_dir_;
    options_.make_draco_visualizers = false;
    options_.make_meshcat_ports_html_thread = false;
    Eigen::VectorXd q1(7);
    Eigen::VectorXd q2(7);
    // small move from view conf
    q1 << -1.47974, 0.161801, -0.472364, -1.66149, 0.45, 1.80, 0.6;
    q2 << -1.47974, 0.161801, -0.472364, -1.66149, 0.403434, 1.62826, 0.389758;
    system_conf_1["iiwa"] = q1;
    system_conf_2["iiwa"] = q2;
    // set the channel, stub, and service
    SetAddress();
    channel_ =
        grpc::CreateChannel(address_, grpc::InsecureChannelCredentials());
    SetService();
    SetStub();
    if (stub_ == nullptr || service_ == nullptr) {
      throw std::runtime_error("Test fixture not properly initialized!");
    }
    // setup server
    server_ = std::make_unique<ServerWrapper>(address_);
    server_->AddService(std::move(service_));
    RunServer();
    // wait for server to come online
    bool connected {false};
    const int wait_for_connected_timeout_ms {2000};
    auto start {hr_clock::now()};
    logging::log()->info(
        "ServiceTest:SetUp: Waiting for server to come online for {:.2f}s...",
        wait_for_connected_timeout_ms / 1000.);
    while (!connected) {
      if (std::chrono::duration_cast<chrono_ms>(hr_clock::now() - start).count()
          > wait_for_connected_timeout_ms) {
        break;
      }
      connected = channel_->GetState(true)
                  == grpc_connectivity_state::GRPC_CHANNEL_READY;
      std::this_thread::sleep_for(chrono_ms(server_poll_ms_));
    }
    ASSERT_TRUE(connected) << "Channel failed to come online!";
    // sleep a bit longer just to be safe
    std::this_thread::sleep_for(chrono_ms(1000));
    logging::log()->info("ServiceTest:SetUp: Server is online!");
  }

  void TearDown() override {
    if (server_thread_ != nullptr) {
      server_->Shutdown();
      while (!server_thread_->joinable()) {
        std::this_thread::sleep_for(chrono_ms(server_poll_ms_));
      }
      server_thread_->join();
    }
    fs::remove_all(temp_dir_);
  }

  proto::PlanContext MakePlanContext() {
    proto::PlanContext context;
    context.set_name("iiwa_boxes");
    const auto temp_iiwa_data_dir {temp_dir_ / "iiwa"};
    const auto dmd_string {common::utils::FileToString(
        temp_iiwa_data_dir / "dmd" / "iiwa_boxes.dmd.yaml")};
    context.set_model_directive_raw(dmd_string);
    // add robot model
    proto::ModelFile robot_file, boxes_file;
    proto::Model robot, boxes;
    robot_file.set_name("iiwa");
    robot_file.set_content(
        common::utils::FileToString(temp_iiwa_data_dir / "urdf" / "iiwa.urdf"));
    robot_file.set_package_name("iiwa_models");
    robot_file.set_format(proto::ModelFormat::MODEL_FORMAT_URDF);
    robot.set_name("iiwa");
    *robot.mutable_file() = robot_file;
    *context.add_models() = robot;
    // add environment model
    boxes_file.set_name("boxes");
    boxes_file.set_content(common::utils::FileToString(
        temp_iiwa_data_dir / "urdf" / "boxes.urdf"));
    boxes_file.set_package_name("iiwa_models");
    boxes_file.set_format(proto::ModelFormat::MODEL_FORMAT_URDF);
    boxes.set_name("environment");
    *boxes.mutable_file() = boxes_file;
    *context.add_models() = boxes;
    return context;
  }

  /**
   * @brief Run the gRPC server for run_duration_ms milliseconds, or until a
   * shutdown is triggered, before automatically shutting off.
   */
  void RunServer() {
    logging::log()->info("ServiceTest:Run: Starting server at {}", address_);
    server_thread_ = std::make_unique<std::thread>(
        std::bind(&ServerWrapper::Run, server_.get()));
  }

  /** Return the port address for the given server. */
  void SetAddress() {
    int address_base {50000};  // only listen on ports 5XXXX
    address_ =
        "localhost:" + std::to_string(address_base + std::rand() % 10000);
  }
  /** Set the service. */
  virtual void SetService() = 0;
  /** Set the stub. */
  virtual void SetStub() = 0;

  const uint64_t kIiwaBoxesHash {10878899324708315470U};
  psc::SystemConf system_conf_1, system_conf_2;
  std::string address_ {""};
  std::shared_ptr<grpc::Channel> channel_ {};
  std::shared_ptr<TStub> stub_ {};
  std::unique_ptr<TService> service_ {};
  std::unique_ptr<ServerWrapper> server_ {};
  std::unique_ptr<std::thread> server_thread_ {nullptr};
  std::atomic<bool> shutdown_triggered_ {false};
  const int server_poll_ms_ {50};
  const std::string system_ {"iiwa"};
  service::utils::ResourceOptions options_;
  // path to data
  fs::path temp_dir_;
};

}  // namespace test
}  // namespace comms
