/*
 * Copyright © 2024 Dexai Robotics. All rights reserved.
 */

/// @file proto_base.h

#pragma once
#include <cstdio>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <type_traits>
#include <typeindex>
#include <typeinfo>

#include <google/protobuf/message.h>
#include <google/protobuf/text_format.h>
#include <google/protobuf/util/json_util.h>
#include <google/protobuf/util/message_differencer.h>

#include "proto/builder.pb.h"
#include "proto/planner.pb.h"
#include "proto/registry.pb.h"
#include "proto/visualizer.pb.h"

namespace planning_service_client {

// Forward declare IO utilities
namespace common {
template <typename Derived>
Derived LoadFromFile(const std::filesystem::path& path, bool binary = false);
template <typename Derived>
Derived LoadFromJsonFile(const std::filesystem::path& path);
}  // namespace common

namespace internal {

/**
 * @brief Abstract base class for types associated with a corresponding Protobuf
 * message. Implements the FromProto and ToProto serialization methods.
 *
 * @tparam Proto Autogenerated protobuf message type.
 */
template <typename Proto>
class ProtoBase {
  static_assert(std::is_base_of_v<google::protobuf::Message, Proto>,
                "Proto must inherit from google::protobuf::Message");

 public:
  bool operator==(const ProtoBase<Proto>& other) const {
    return google::protobuf::util::MessageDifferencer::Equals(
        ToProtoImpl(), other.ToProtoImpl());
  }
  /** Virtual destructor. */
  virtual ~ProtoBase() = default;

  /**
   * @brief Converts the object to a string representation.
   *
   * @param binary If true, output as packed binary string. Otherwise, use text
   * format.
   *
   */
  const std::string ToString(bool binary = false) const {
    const auto msg {ToProtoImpl()};
    std::string output;
    if (binary) {
      if (!msg.SerializeToString(&output)) {
        throw std::runtime_error(
            "Failed to convert proto message to binary format string.");
      }
    } else {
      if (!google::protobuf::TextFormat::PrintToString(msg, &output)) {
        throw std::runtime_error(
            "Failed to convert proto message to text format string.");
      }
    }
    return output;
  }
  /**
   * @brief Converts the object to a JSON string representation.
   *
   */
  const std::string ToJson() const {
    const auto msg {ToProtoImpl()};
    std::string output;
    google::protobuf::util::JsonPrintOptions options;
    options.preserve_proto_field_names = true;
    if (!google::protobuf::util::MessageToJsonString(msg, &output, options)
             .ok()) {
      throw std::runtime_error(
          "Failed to convert proto message to JSON format string.");
    }
    return output;
  }

  using ProtoType = Proto;

 protected:
  /** Pure virtual method to implement ToProto */
  virtual Proto ToProtoImpl() const = 0;

  /** Pure virtual method to implement FromProto */
  virtual void FromProtoImpl(const Proto& msg) = 0;

  // Friend declarations for serialization functions
  template <typename DerivedProto>
  friend DerivedProto ToProto(const ProtoBase<DerivedProto>& obj);

  template <typename Derived, typename DerivedProto>
  friend Derived FromProto(const DerivedProto& msg);

  template <typename Derived>
  friend Derived FromJson(const std::string_view json);

  template <typename Derived>
  friend Derived FromString(const std::string_view str, bool binary);

  // File IO utilities
  template <typename Derived>
  friend Derived common::LoadFromFile(const std::filesystem::path& path,
                                      bool binary);
  template <typename Derived>
  friend Derived common::LoadFromJsonFile(const std::filesystem::path& path);
};

// Type trait to detect if a type derives from ProtoBase
template <typename T, typename = void>
struct is_proto_base : std::false_type {};

template <typename T>
struct is_proto_base<T, std::void_t<typename T::ProtoType>>
    : std::is_base_of<ProtoBase<typename T::ProtoType>, T> {};

template <typename T>
inline constexpr bool is_proto_base_v = is_proto_base<T>::value;

/**
 * @brief Converts a proto message to a derived object.
 * @param msg The proto message to convert.
 * @return The derived object.
 */
template <typename Derived, typename DerivedProto = typename Derived::ProtoType>
Derived FromProto(const DerivedProto& msg) {
  static_assert(std::is_base_of_v<ProtoBase<DerivedProto>, Derived>,
                "Derived must inherit from ProtoBase");
  // Create the derived object using smart pointers for safety
  auto obj_derived = std::make_unique<Derived>();
  // Access the ProtoBase interface
  auto* obj = static_cast<ProtoBase<DerivedProto>*>(obj_derived.get());
  // Perform the deserialization
  obj->FromProtoImpl(msg);
  // Transfer ownership to the caller
  return std::move(*obj_derived);
}

template <typename DerivedProto>
DerivedProto ToProto(const ProtoBase<DerivedProto>& obj) {
  return obj.ToProtoImpl();
}

// Protobuf scalar types cover numeric types, strings, and booleans
template <typename T>
inline constexpr bool is_protobuf_scalar_v =
    std::is_integral_v<T> || std::is_floating_point_v<T>
    || std::is_same_v<T, bool>;

/** Scalar vector Protobuf deserialization. */
template <typename T, typename = std::enable_if_t<is_protobuf_scalar_v<T>>>
std::vector<T> FromProto(
    const google::protobuf::RepeatedField<T>& repeated_field) {
  return std::vector<T>(repeated_field.begin(), repeated_field.end());
}
/** Scalar vector Protobuf serialization. */
template <typename T, typename = std::enable_if_t<is_protobuf_scalar_v<T>>>
google::protobuf::RepeatedField<T> ToProto(const std::vector<T>& vec) {
  google::protobuf::RepeatedField<T> repeated_field;
  for (const auto& item : vec) {
    repeated_field.Add(item);
  }
  return repeated_field;
}

/** String vector Protobuf deserialization. */
inline std::vector<std::string> FromProto(
    const google::protobuf::RepeatedPtrField<std::string>& repeated_field) {
  return std::vector<std::string>(repeated_field.begin(), repeated_field.end());
}
/** String vector Protobuf serialization. */
inline google::protobuf::RepeatedPtrField<std::string> ToProto(
    const std::vector<std::string>& vec) {
  google::protobuf::RepeatedPtrField<std::string> repeated_field;
  for (const auto& item : vec) {
    repeated_field.Add()->assign(item);
  }
  return repeated_field;
}

/** Nested ProtoBase vector Protobuf deserialization. */
template <typename T,
          typename = std::enable_if_t<is_proto_base_v<T>
                                      && !std::is_same_v<T, std::string>>>
std::vector<T> FromProto(
    const google::protobuf::RepeatedPtrField<typename T::ProtoType>&
        repeated_field) {
  std::vector<T> result;
  result.reserve(repeated_field.size());
  for (const auto& item : repeated_field) {
    result.push_back(FromProto<T>(item));
  }
  return result;
}

/** Nested ProtoBase vector Protobuf serialization. */
template <typename T,
          typename = std::enable_if_t<is_proto_base_v<T>
                                      && !std::is_same_v<T, std::string>>>
google::protobuf::RepeatedPtrField<typename T::ProtoType> ToProto(
    const std::vector<T>& vec) {
  google::protobuf::RepeatedPtrField<typename T::ProtoType> repeated_field;
  for (const auto& item : vec) {
    repeated_field.Add()->CopyFrom(ToProto(item));
  }
  return repeated_field;
}

/**
 * @brief Convert a JSON string to a ProtoBase-derived object.
 *
 * @tparam Derived The derived ProtoBase type.
 * @param j The JSON string to convert.
 * @return Derived The converted ProtoBase-derived object.
 */
template <typename Derived>
Derived FromJson(const std::string_view j) {
  typename Derived::ProtoType msg;
  auto status = google::protobuf::util::JsonStringToMessage(j.data(), &msg);
  if (!status.ok()) {
    throw std::runtime_error("Failed to parse JSON string to proto message: "
                             + std::string(status.message()));
  }
  return FromProto<Derived>(msg);
}

/**
 * @brief Convert a string (binary or text format) to a ProtoBase-derived
 * object.
 *
 * @tparam Derived The derived ProtoBase type.
 * @param s The string to convert.
 * @param binary If true, interpret the string as binary format. Otherwise,
 * interpret as text format.
 * @return Derived The converted ProtoBase-derived object.
 */
template <typename Derived>
Derived FromString(const std::string_view s, bool binary = false) {
  typename Derived::ProtoType msg;
  bool success {false};
  if (binary) {
    if (s.size() > static_cast<std::size_t>(std::numeric_limits<int>::max())) {
      throw std::runtime_error(
          "FromString: input size exceeds INT_MAX and cannot be safely cast "
          "for ParseFromArray.");
    }
    success = msg.ParseFromArray(s.data(), static_cast<int>(s.size()));
  } else {
    success = google::protobuf::TextFormat::ParseFromString(s.data(), &msg);
  }
  if (!success) {
    throw std::runtime_error("Failed to parse string to proto message.");
  }
  return FromProto<Derived>(msg);
}

}  // namespace internal

// Bring utility functions into the top-level namespace
using internal::FromJson;
using internal::FromProto;
using internal::FromString;
using internal::ToProto;

}  // namespace planning_service_client
