/*
 * Copyright © 2024 Dexai Robotics. All rights reserved.
 */

/// @file system_property.h

#pragma once

#include "planning_service_client/internal/proto_base.h"

namespace planning_service_client {
namespace internal {

/**
 * @brief Abstract base class for "system" types, in which each constituent
 * element of the system is mapped by name to its corresponding value.
 *
 * @tparam T The type of the system element.
 * @tparam SystemProto Autogenerated protobuf message type.
 */
template <typename T, typename SystemProto>
class SystemProperty : public internal::ProtoBase<SystemProto> {
 public:
  SystemProperty() = default;
  SystemProperty(const std::map<std::string, T>& data) : data_(data) {}
  SystemProperty(std::initializer_list<std::pair<const std::string, T>> init)
      : data_(init) {}
  // Type aliases for STL compatibility
  using key_type = std::string;
  using mapped_type = T;
  using value_type = std::pair<const key_type, mapped_type>;
  using iterator = typename std::map<key_type, mapped_type>::iterator;
  using const_iterator =
      typename std::map<key_type, mapped_type>::const_iterator;

  // overload [] operator
  T& operator[](const std::string& key) {
    return data_[key];
  }
  // @deprecated Use contains() instead.
  bool has_key(const std::string& key) const {
    return data_.find(key) != data_.end();
  }

  bool contains(const std::string& key) const {
    return data_.contains(key);
  }

  auto find(const std::string& key) const {
    return data_.find(key);
  }

  const T& at(const std::string& key) const {
    return data_.at(key);
  }

  bool operator==(const SystemProperty& other) const {
    return data_ == other.data_;
  }

  auto insert(const value_type& pair) {
    return data_.insert(pair);
  }

  auto insert(iterator pos, const value_type& pair) {
    return data_.insert(pos, pair);
  }

  /** Return an iterator to the first element. */
  auto begin() {
    return data_.begin();
  }

  /** Return an iterator to the element following the last element. */
  auto end() {
    return data_.end();
  }

  /** Return a const iterator to the first element. */
  auto begin() const {
    return data_.begin();
  }

  /** Return a const iterator to the element following the last element. */
  auto end() const {
    return data_.end();
  }

  int size() const {
    return data_.size();
  }

  /** Emplaces a new element in the map. */
  auto emplace(const std::string& key, const T& value) {
    return data_.emplace(key, value);
  }

  const std::map<std::string, T>& data() const {
    return data_;
  }

  bool empty() const {
    return data_.empty();
  }

  void erase(const std::string& key) {
    data_.erase(key);
  }

 private:
  SystemProto ToProtoImpl() const override {
    SystemProto system_proto;
    for (const auto& [key, obj] : data_) {
      (*system_proto.mutable_data())[key] = ToProto(obj);
    }
    return system_proto;
  }

  void FromProtoImpl(const SystemProto& msg) override {
    data_.clear();
    for (const auto& [key, obj_proto] : msg.data()) {
      data_[key] = FromProto<T>(obj_proto);
    }
  }

  std::map<std::string, T> data_;
};

}  // namespace internal
}  // namespace planning_service_client
