# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Create clean gh-pages branch
        run:  git checkout -b gh-pages
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: update the system
        run: sudo apt-get update
      - name: install module in virtual env
        run: |
          python -m venv docs_env
          source docs_env/bin/activate
          pip install --upgrade pip pip==23.0.0 # Peg version as venv is not propograted to subprocess.run call in 23.1+ in setup.py
          pip install -r client/python/planning_service_client/requirements.txt  # Install dependencies
          pip install -U sphinx
          pip install sphinx_rtd_theme
      - name: Install planning_service_client
        run: |
          source docs_env/bin/activate
          cd client/python/planning_service_client
          echo "cleaning"
          rm -rf build
          rm -rf dist
          rm -rf *.egg-info
          pip install . -v
      - name: make documentation
        run: |
          ./generate_client_docs.sh
          mv docs/website/* docs/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PlanningServiceDocs }}
          user_name: 'SonyResearch'
          user_email: 'sadra.sadraddini@dexai.com'
          publish_dir: ./docs
          force_orphan: true
