#!/bin/bash
set -eufo pipefail

# Consume the coverage report generated by the unit tests and generate an HTML report.

PROJECT_ROOT="$(dirname $(dirname $(realpath $0)))"
COVERAGE_REPORT_DIRNAME=coverage
COVERAGE_REPORT_PATH=$(bazel info output_path)/_coverage/_coverage_report.dat

if [[ ! -f ${COVERAGE_REPORT_PATH} ]]; then
  echo "Coverage report not found at ${COVERAGE_REPORT_PATH}"
  exit 1
fi

echo "Generating HTML coverage report at ${PROJECT_ROOT}/${COVERAGE_REPORT_DIRNAME}..."
genhtml --branch-coverage -o ${PROJECT_ROOT}/${COVERAGE_REPORT_DIRNAME} ${COVERAGE_REPORT_PATH}
