/*
 * Copyright © 2023 Dexai Robotics. All rights reserved.
 */
#include "CLI/CLI.hpp"
#include "iris_builder_app.h"
#include "planning_service/common/misc_utils.h"
#include "planning_service/common/string_utils.h"

int main(int argc, char* argv[]) {
  logging::create_log("iris_builder-" + common::utils::GetTag());
  //// Create command line interface
  CLI::App app {
      "IRIS builder app which can generate IRIS regions for a given model and "
      "set of constraints"};
  int verbosity {3};
  std::string help_msg {
      fmt::format("Verbosity and logging level.  Default: {}", verbosity)};
  app.add_option("-v, --verbosity", verbosity, help_msg);

  size_t queue_capacity {20};
  app.add_option("-c, --queue_capacity", queue_capacity,
                 "Maximum number of IRIS generation requests which can wait in "
                 "the queue.");

  size_t max_jobs {20};
  app.add_option("-n,--max_jobs", max_jobs,
                 "Maximum number of IRIS generation jobs which can be run at a "
                 "given time.");

  std::string system_name {""};
  app.add_option("--system_name", system_name,
                 "Target system and top-level namespace for all data consumed "
                 "and generated by the application")
      ->required();
  bool require_all_resources {false};
  app.add_flag(
      "--require_all_resources", require_all_resources,
      "Require all resources to be loaded before starting the service");

  std::string include_names_str = "";
  app.add_option("-i, --include_names", include_names_str,
                 "List of names that systems must contain in their DMDs to be "
                 "included");
  CLI11_PARSE(app, argc, argv);

  // Set the logging level
  logging::set_verbosity(verbosity);

  // Parse include names to ResourceOptions
  std::optional<std::vector<std::string>> dmd_contains_names {};
  if (!include_names_str.empty()) {
    dmd_contains_names = common::utils::split_string(include_names_str, ',');
  }

  // TODO(@davebambrick): make addresses configurable

  const std::string iris_addr {"0.0.0.0:5150"};
  try {
    service::utils::ResourceOptions options;
    options.require_all_resources = require_all_resources;
    options.dmd_contains_names = dmd_contains_names;
    IrisGenerationApp iga {iris_addr, system_name, options, queue_capacity,
                           max_jobs};
    iga.Run();
  } catch (const std::exception& e) {
    fmt::print("IrisGenerationApp:Run: Exception: {}\n", e.what());
    return EXIT_FAILURE;
  }
  return 0;
}
