/*
 * Copyright © 2023 Dexai Robotics. All rights reserved.
 */
#include "CLI/CLI.hpp"
#include "motion_planner_app.h"
#include "planning_service/common/misc_utils.h"
#include "planning_service/common/string_utils.h"

int main(int argc, char* argv[]) {
  logging::create_log("motion_planner-" + common::utils::GetTag());
  //// Create command line interface
  CLI::App app {"Motion planning service"};
  int verbosity {3};
  app.add_option(
      "-v, --verbosity", verbosity,
      fmt::format("Verbosity and logging level.  Default: {}", verbosity));

  std::string system_name {""};
  app.add_option("--system_name", system_name,
                 "Target system and top-level namespace for all data consumed "
                 "and generated by the application")
      ->required();
  bool require_all_resources {false};
  app.add_flag(
      "-r,--required", require_all_resources,
      "Require all resources to be loaded before starting the service");

  bool load_resources_on_init {false};
  app.add_flag("-l,--load_on_init", load_resources_on_init,
               "Load all resources on initialization. If false, resources are "
               "loaded on demand");

  bool enable_drake_logging {false};
  app.add_flag("--enable_drake_logging", enable_drake_logging,
               "Enable drake logging. Default: false");

  std::string include_names_str = "";
  app.add_option("-i, --include_names", include_names_str,
                 "List of names that systems must contain in their DMDs to be "
                 "included");
  CLI11_PARSE(app, argc, argv);

  // Set the logging level
  logging::set_verbosity(verbosity);

  if (!enable_drake_logging) {
    logging::disable_drake_logging();
  }

  // Parse include names to ResourceOptions
  std::optional<std::vector<std::string>> dmd_contains_names {};
  if (!include_names_str.empty()) {
    dmd_contains_names = common::utils::split_string(include_names_str, ',');
  }

  // TODO(@davebambrick): make addresses configurable

  const std::string planning_addr {"0.0.0.0:5050"};
  try {
    service::utils::ResourceOptions options;
    options.require_all_resources = require_all_resources;
    options.load_resources_on_init = load_resources_on_init;
    options.dmd_contains_names = dmd_contains_names;
    MotionPlannerApp mpa {planning_addr, system_name, options};
    mpa.Run();
  } catch (const std::exception& e) {
    fmt::print("MotionPlannerApp:Run: Exception: {}\n", e.what());
    return EXIT_FAILURE;
  }
  return 0;
}
