/*
 * Copyright © 2023 Dexai Robotics. All rights reserved.
 */
#include "CLI/CLI.hpp"
#include "planning_service/common/misc_utils.h"
#include "visualizer_app.h"
int main(int argc, char* argv[]) {
  logging::create_log("visualizer-" + common::utils::GetTag());
  //// Create command line interface
  CLI::App app {
      "Visualizer app to display robot model, generated IRIS regions, and "
      "other things"};
  int verbosity {4};
  std::string help_msg {fmt::format("Verbosity and logging level.")};
  app.add_option("-v, --verbosity", verbosity, help_msg)->capture_default_str();

  std::string system_name {""};
  app.add_option("--system_name", system_name,
                 "Target system and top-level namespace for all data consumed "
                 "and generated by the application")
      ->required();

  bool enable_sliders {false};
  auto sliders_flag =
      app.add_flag("--sliders,!--no-sliders", enable_sliders,
                   "Enable joint sliders in the visualizer GUI");
  bool enable_set_configuration {false};
  auto set_configuration_flag = app.add_flag(
      "--set-configuration,!--no-set-configuration", enable_set_configuration,
      "Enable setting joint positions via external calls");
  bool default_init {false};
  auto default_init_flag = app.add_flag(
      "--default-init,!--no-default-init", default_init,
      "On startup, load a default robot model into the visualizer");

  CLI11_PARSE(app, argc, argv);

  // Set the logging level
  logging::set_verbosity(verbosity);

  const auto visualizer_options_path {fs::path("/data") / system_name
                                      / VIZ_OPTIONS_FILE};
  auto options {
      drake::yaml::LoadYamlFile<service::visualization::VisualizerOptions>(
          visualizer_options_path)};
  // Only override options if flags were explicitly set
  options.enable_sliders =
      sliders_flag->count() ? enable_sliders : options.enable_sliders;
  options.enable_set_configuration = set_configuration_flag->count()
                                         ? enable_set_configuration
                                         : options.enable_set_configuration;
  options.default_init =
      default_init_flag->count() ? default_init : options.default_init;
  // TODO(@davebambrick): make addresses configurable
  const std::string addr {"0.0.0.0:5550"};
  VisualizerApp visualizer_app {addr, system_name, options};
  visualizer_app.Run();
  return 0;
}
